<article class="blogPost">
    <header>
        <h3><a href="<?= $this->postUrl($this->post) ?>">Day <?= $this->post->getDay() ?>: <?= $this->post->title ?></a></h3>
        <div class="author">
            Author: <hh-user name="<?= $this->post->author->username ?>" />
        </div>
        <div>Posted: <time><?= $this->date($this->post->date) ?></time></div>
    </header>
    <?= $this->post->body ?>
    <!--
    <section>
        <h4>Comments</h4>
        <article>
            <div id="disqus_thread"></div>
        </article>
    </section>
    -->
</article>
